tsdashboard/info/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField, BooleanField, SelectField, IntegerField, TextAreaField
from wtforms.validators import DataRequired, URL
from wtforms.fields.html5 import DateField


class InfoForm(FlaskForm): # pass
    zanimivi_primeri = TextAreaField('zanimivi primeri', render_kw={"placeholder": "zanimiv primer ...", "onkeyup": "textareaAutoHeight(this)", "onclick": "ustvariDatum(this.id)"})
    zanimivi_primeri_cas = DateField('zanimivi_primeri_cas', format='%Y-%m-%d')
    opazanja = TextAreaField('opažanja', render_kw={"placeholder": "opazil sem ...", "onkeyup": "textareaAutoHeight(this)", "onclick": "ustvariDatum(this.id)"})
    opazanja_cas = DateField('opazanja_cas', format='%Y-%m-%d')
    dolgotrajne_napake = TextAreaField('dolgotrajne napake', render_kw={"placeholder": "tale inc se vleče že ...", "onkeyup": "textareaAutoHeight(this)", "onclick": "ustvariDatum(this.id)"})
    dolgotrajne_napake_cas = DateField('dolgotrajne_napake_cas', format='%Y-%m-%d')
    projekti = TextAreaField('projekti', render_kw={"placeholder": "sodeloval sem pri ...", "onkeyup": "textareaAutoHeight(this)", "onclick": "ustvariDatum(this.id)"})
    projekti_cas = DateField('projekti_cas', format='%Y-%m-%d')
    ostalo = TextAreaField('ostalo', render_kw={"placeholder": "mogoče lahko izboljšamo ...", "onkeyup": "textareaAutoHeight(this)", "onclick": "ustvariDatum(this.id)"})
    ostalo_cas = DateField('ostalo_cas', format='%Y-%m-%d')

    submit = SubmitField('dodaj info')

tsdashboard/apis/routes.py
from flask import url_for, render_template, redirect, request, flash, Blueprint
from flask_login import current_user, login_required

from tsdashboard import db, scheduler
from tsdashboard.models import ApiModel
from tsdashboard.apis.forms import ApiForm
from tsdashboard.utile import app_scheduler
from tsdashboard.utile.siem import Qradar, QradarConfig

apis = Blueprint('apis', __name__)

@apis.route('/APIs')
@login_required
def APIs():
    apis = ApiModel.query.all()
    return render_template('allAPIs.html', title='APIs', name='APIs', apis=apis)

@apis.route('/APIs/add', methods=['GET', 'POST'])
@login_required
def APIadd():
    form = ApiForm()
    if form.validate_on_submit():
        siem = ApiModel(
            ime=form.ime_uporabnika.data,
            izbor=form.izbor_SIEM.data,
            api_key=form.api_kluc.data,
            url=form.url.data,
            barva=request.form.getlist('apiBarva')[0],
            admin_dostop=form.api_admin_dostop.data,
            statistika=form.izdelava_statistike.data,
            cas_spremljanja=form.cas_preverbe.data,
            cas_opozorila=form.cas_opozorila.data,
            user_id=current_user.username
            )
        
        db.session.add(siem)
        db.session.commit()
        flash(f'uspešno dodan SIEM API', 'success')
        if form.izbor_SIEM.data == "qradar":
            if form.api_admin_dostop.data is True:
                config = QradarConfig(form.ime_uporabnika.data, form.api_kluc.data, form.url.data, form.api_admin_dostop.data)
                config.setDomains()
                config.setOffenses()
                scheduler.add_job(id="{}".format(form.ime_uporabnika.data), func=app_scheduler.updateQradar, trigger="interval", seconds=form.cas_preverbe.data, replace_existing=True)
            else:
                config = QradarConfig(form.ime_uporabnika.data, form.api_kluc.data, form.url.data, form.api_admin_dostop.data)
                config.setOffenses()
                scheduler.add_job(id="{}".format(form.ime_uporabnika.data), func=app_scheduler.updateQradar, trigger="interval", seconds=form.cas_preverbe.data, replace_existing=True)
        elif form.izbor_SIEM.data == "mcafee":
            pass
        elif form.izbor_SIEM.data == "splunk":
            pass
        else:
            print("nic izbranega")
        return redirect(url_for('apis.APIs'))
    return render_template('APIadd.html', title="Dodaj API", name='Dodaj API', form=form)

@apis.route('/APIs/<int:id>/edit', methods=['GET', 'POST'])
@login_required
def APIedit(id):
    #################################################################
    api = ApiModel.query.get_or_404(id)
    form = ApiForm()
    if form.validate_on_submit():
        api.ime = form.ime_uporabnika.data
        api.izbor = form.izbor_SIEM.data
        api.api_key = form.api_kluc.data
        api.url = form.url.data
        api.barva = request.form.getlist('apiBarva')[0]
        api.admin_dostop = form.api_admin_dostop.data
        api.statistika = form.izdelava_statistike.data
        api.cas_spremljanja = form.cas_preverbe.data
        api.cas_opozorila = form.cas_opozorila.data
        db.session.commit()
        flash('uspešno si spremenil api', 'success')
        return redirect(url_for('apis.APIs'))
    elif request.method == 'GET':
        form.ime_uporabnika.data = api.ime
        form.izbor_SIEM.data = api.izbor
        form.api_kluc.data = api.api_key
        form.url.data = api.url
        barvica = api.barva
        form.api_admin_dostop.data = api.admin_dostop
        form.izdelava_statistike.data = api.statistika
        form.cas_preverbe.data = api.cas_spremljanja
        form.cas_opozorila.data = api.cas_opozorila
    return render_template('APIedit.html', title='API edit', name='Popravi API', form=form, barvica=barvica, legend='API edit')
    
@apis.route('/APIs/<int:id>/delete', methods=['GET', 'POST'])
@login_required
def APIdelete(id):
    api_id = ApiModel.query.get_or_404(id)
    db.session.delete(api_id)
    db.session.commit()
    flash('zbrisu si en api iz seznama', 'success')
    return redirect(url_for('apis.APIs'))

tsdashboard/info/routes.py
from flask import Blueprint, render_template, redirect, flash
from flask_login import current_user, login_required

from tsdashboard.info.forms import InfoForm


info = Blueprint('info', __name__)

@info.route('/info')
@login_required
def informacije(): # pass
    form = InfoForm()
    if form.validate_on_submit():
        info = InfoModel(
            zanimivi_primeri=form.zanimivi_primeri.data,
            zanimivi_primeri_cas=form.zanimivi_primeri_cas.data,
            opazanja=form.opazanja.data,
            opazanja_cas=form.opazanja_cas.data,
            dolgotrajne_napake=form.dolgotrajne_napake.data,
            dolgotrajne_napake_cas=form.dolgotrajne_napake_cas.data,
            projekti=form.projekti.data,
            projekti_cas=form.projekti_cas.data,
            ostalo=form.ostalo.data,
            ostalo_cas=form.ostalo_cas.data)


        db.session.add(info)
        db.session.commit()
        flash(f'uspešno dodan SIEM API', 'success')
        return redirect(url_for('APIs'))
    return render_template('info.html', title='Informacije', name='Info', form=form)

@info.route('/info/<datum>')
@login_required
def dogodek(datum):
    return render_template('dogodek.html', title='Dogodki', name=datum, data=datum)

tsdashboard/main/routes.py
from flask import Blueprint, render_template

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/domov')
@main.route('/index')
@main.route('/home')

# @login_required
def home():
    return render_template('home.html', title='Home', name='Dom')

@main.route('/about') 
def about():
    return render_template('about.html', title='About', name='About')

tsdashboard/timers/routes.py
from flask import url_for, render_template, redirect, request, flash, Blueprint
from flask_login import current_user, login_required

from tsdashboard import db, scheduler


casi  = Blueprint('timers', __name__)

@casi.route('/timers', methods=['GET'])
@login_required
def timers():
    data = {}
    jobs = scheduler.get_jobs()
    # test_tmp = scheduler.print_jobs()
    for i in range(len(jobs)):
        data[i] = {"name": jobs[i].name, "id": jobs[i].id, "trigger": jobs[i].trigger, "next_run_time": jobs[i].next_run_time, "func": jobs[i].func_ref}
        print(type(jobs[i].trigger))
    return render_template('scheduler.html', title='scheduler', name='scheduler', jobs=jobs, data=data)

@casi.route('/timers/<string:id>/pause', methods=['GET'])
def pause_timer(id):
    if id == "ALL":
        scheduler.pause()
    else:
        scheduler.pause_job(id)
    return redirect(url_for('timers.timers'))

@casi.route('/timers/<string:id>/resume', methods=['GET'])
def resume_timer(id):
    if id == "ALL":
        scheduler.resume()
    else:
        scheduler.resume_job(id)
    return redirect(url_for('timers.timers'))

@casi.route('/timers/add', methods=['GET', 'POST'])
def add_timer(): pass

@casi.route('/timers/<string:id>/edit', methods=['GET', 'POST'])
def edit_timer(id): 
    if request.method == 'POST':
        print(request.form["triggerName"])
        print(request.form["triggerTrig"])
        scheduler.modify_job(id, name=request.form["triggerName"])
        scheduler.scheduler.reschedule_job(id, trigger="cron", minute='*')
    return redirect(url_for('timers.timers'))
    
    # if request.method == 'POST': pass

@casi.route('/timers/<string:id>/delete', methods=['GET'])
def delete_timer(id):
    scheduler.remove_job(id)
    return redirect(url_for('timers.timers'))

tsdashboard/users/routes.py
from flask import Blueprint

from flask import Flask, url_for, render_template, redirect, request, render_template_string
from flask_login import login_required, logout_user, login_user
from flask_ldap3_login.forms import LDAPLoginForm

from tsdashboard import db, login_manager, ldap_manager
from tsdashboard.models import UserModel, ApiModel
from tsdashboard.utile.siem import Qradar

users = Blueprint('users', __name__)

@users.route('/manual_login')
def manual_login():
    app.ldap3_login_manager.authenticate('username', 'password')

@users.route('/login', methods=['GET', 'POST'])
def login():
    template = """
    {{ get_flashed_messages() }}
    {{ form.errors }}
    <form method="POST">
        <label>Username{{ form.username() }}</label>
        <label>Password{{ form.password() }}</label>
        {{ form.submit() }}
        {{ form.hidden_tag() }}
    </form>
    """
    form = LDAPLoginForm()

    if form.validate_on_submit():
        # Successfully logged in, We can now access the saved user object via form.user.
        login_user(form.user)  # Tell flask-login to log them in.
        next_page = request.args.get('next')
        return redirect(next_page) if next_page else redirect(url_for('main.home'))
        # return redirect('/')  # Send them home

    return render_template_string(template, form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route('/profil/<username>')
@login_required
def profil(username):
    return render_template('profil.html', title='Profil', name='Profil', data=username)

@users.route('/user/test')
def testfunc():
    srch = Qradar()
    data = srch.getUserAdmin()

    return render_template('test.html', title="user test", name='user test', data=data)

tsdashboard/templates/APIadd.html
{% extends "layout.html" %}
{% block head %} 
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/APIs.css') }}">
    <script src="{{ url_for('static', filename='js/API.js') }}" integrity="" crossorigin="anonymous"></script>
{% endblock head %}

{% block body %}

<form action="" method="POST">
    {{ form.csrf_token }}
    
    <div class="form-group row">
        {{ form.ime_uporabnika.label(class="col-sm-2 col-form-label") }}
        {% if form.ime_uporabnika.errors %}
            <div class="col-sm-10">
                {{ form.ime_uporabnika(class="form-control is-invalid") }}
            </div>
            <div class="invalid-feedback">
                {% for error in form.ime_uporabnika.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </div>
        {% else %}
            <div class="col-sm-10">
                {{ form.ime_uporabnika(class="form-control") }}
            </div>
        {% endif %}
    </div>

    <div class="form-group row">
        {{ form.izbor_SIEM.label(class="col-sm-2 col-form-label") }}
        <div class="col-sm-10">
            {{ form.izbor_SIEM(class="custom-select my-1 mr-sm-2") }}
        </div>
        <div class="invalid-feedback">
            {% for error in form.izbor_SIEM.errors %}
                <li>{{ error }}</li>
            {% endfor %}
            Please provide a valid city.
        </div>
    </div>

    <div class="form-group row">
        {{ form.api_kluc.label(class="col-sm-2 col-form-label") }}
        <div class="col-sm-10">
            {{ form.api_kluc(class="form-control") }}
        </div>
    </div>

    <div class="form-group row">
        {{ form.url.label(class="col-sm-2 col-form-label") }}
        <div class="col-sm-10">
            {{ form.url(class="form-control") }}
        </div>
    </div>

    <fieldset class="form-group">
        <div class="row">
            <legend class="col-form-label col-sm-2 pt-0">Administracija</legend>
            <div class="col-sm-10">

                <div class="form-check">
                    <input type="color" class="form-color-input" name="apiBarva" id="apiBarva", value="{{ barvica }}">
                    <label class="form-color-label" for="apiBarva">Barva</label>
                </div>
                
                <div class="form-check">
                    {{ form.api_admin_dostop(class="form-check-input") }}
                    {{ form.api_admin_dostop.label(class="form-check-label") }}
                </div>

                <div class="form-check">
                    {{ form.izdelava_statistike(class="form-check-input") }}
                    {{ form.izdelava_statistike.label(class="form-check-label") }}
                </div>

            </div>
        </div>
    </fieldset>
    
    <div class="form-group row">
        {{ form.cas_preverbe.label(class="col-sm-2 col-form-label") }}
        <div class="col-sm-10">
            {{ form.cas_preverbe(class="form-control", placeholder="sekunde") }}
        </div>
    </div>
    <div class="form-group row">
        {{ form.cas_opozorila.label(class="col-sm-2 col-form-label") }}
        <div class="col-sm-10">
            {{ form.cas_opozorila(class="form-control", placeholder="sekunde") }}
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-10">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </div>
</form>

{% endblock body %}

{% block optional_js %}
<script>
    document.getElementById('naslov').innerHTML = 'DashBoard - ' + '{{ name }}';
</script>
{%endblock optional_js %}

tsdashboard/templates/allAPIs.html
{% extends "layout.html" %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/APIs.css') }}" integrity="" crossorigin="anonymous">
    <script src="{{ url_for('static', filename='js/APIs.js') }}" integrity="" crossorigin="anonymous"></script>
{% endblock head %}

{% block body %}

<nav>
    <ul class="nav nav-tabs">
        <li class="nav-item">
        <a class="nav-link active" href="#">kaj imamo</a>
        </li>
        <li class="nav-item">
        <a class="nav-link disabled" href="#">Siem predloga</a>
        </li>
        <li class="nav-item ml-auto">
            <a href="{{ url_for('apis.APIadd') }}" class="nav-link material-icons">add</a>
        </li>
    </ul>
</nav>

<table id="api-tabela" class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th scope="col">ime</th>
            <th scope="col">tip</th>
            <th scope="col">API</th>
            <th scope="col">url</th>
            <th scope="col">preveri</th>
            <th scope="col">opozori</th>
            <th scope="col">popravi</th>
            <th scope="col">zbriši</th>
        </tr> 
    </thead>

    {% for api in apis %}
        <tr id="id-{{ api.id }}" style="color:{{ api.barva }}"}> 
            <th>{{ api.ime }}</th>
            <td>{{ api.izbor }}</td>
            <td>{{ api.api_key }}</td>
            <td>{{ api.url }}</td>
            <td>{{ api.cas_spremljanja }}</td>
            <td>{{ api.cas_opozorila }}</td>
            <td>
                <a href="{{ url_for('apis.APIedit', id=api.id) }}" id="btn-id-{{ api.id }}" class="btn material-icons">edit</a>
            </td>
            <td>
                <a href="{{ url_for('apis.APIdelete', id=api.id) }}" id="btn-id-{{ api.id }}" class="btn material-icons">delete_outline</a>
            </td>
        </tr>
    {% endfor %}
</table>


{% endblock body %}

{% block optional_js %}
<script>
    let siemi = "{{ apis|safe }}";
    nastaviTabelo(siemi);
    document.getElementById('naslov').innerHTML = 'DashBoard - ' + '{{ name }}';
</script>
{% endblock optional_js %}

tsdashboard/templates/dogodek.html
{% extends "layout.html" %}
{% block head %} 
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/dogodek.css') }}">
    <script src="{{ url_for('static', filename='js/dogodek.js') }}" integrity="" crossorigin="anonymous"></script>
{% endblock head %}
{% block body %}
<div id="dogodek-container-div">
    <div id="naslovni-del">
        <a id="predhodni-mesec" href="#" class="btn">&laquo;</a>
        <a id="predhodni-dan" href="#" class="btn">&#8249;</a>
        <h1>{{ name }}</h1>
        <a id="naslednji-dan" href="#" class="btn">&#8250;</a>
        <a id="naslednji-mesec" href="#" class="btn">&raquo;</a>
    </div>


    <fieldset class="skrit">
        <legend>zanimivi primeri</legend>
    </fieldset>
    <fieldset class="skrit">
        <legend>opažanja</legend>
    </fieldset>
    <fieldset class="skrit">
        <legend>dolgotrajni dogodki</legend>
    </fieldset>
    <fieldset class="skrit">
        <legend>projekti</legend>
    </fieldset>
    <fieldset class="skrit">
        <legend>ostalo</legend>
    </fieldset>
</div>
{% endblock body %}

{% block optional_js %}
<script>
    let name = "{{ name }}";
    urediNaslov(name);
    document.getElementById('naslov').innerHTML = 'DashBoard - ' + '{{ name }}';
</script>
{%endblock optional_js %}

tsdashboard/templates/layout.html
<!DOCTYPE html>
<html>
    <head lang="en">
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        {% if title %}
            <title>Naslov - {{ title }}</title>
        {% else %}
            <title>Naslov</title>
        {% endif %}

        <link rel="icon" href="{{ url_for('static', filename='img/favicon.jpg') }}" type="image/jpg">
        <!-- CSS -->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/mainCSS.css') }}" integrity="" crossorigin="anonymous">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <!-- Javascript - required -->
        <script src="{{ url_for('static', filename='js/mainJS.js') }}" integrity="" crossorigin="anonymous"></script>

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

        {% block head %} {% endblock head %}

    </head>
    <body>
        <header id="main-header" class="main-header"> 
            <section class="navbar-brand d-flex">
                <div class="flex-shrink-1"><a href="{{ url_for('main.home') }}"><img id="tslogo" src="{{ url_for('static', filename='img/tslogo.svg') }}" alt=""></a></div>
                <div class="d-flex flex-grow-1 justify-content-center align-self-center"><a href="{{ url_for('main.home') }}"><h1 id="naslov">DashBoard</h1></a></div>
            </section>
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-item nav-link active" href="{{ url_for('main.home') }}">Domov<span class="sr-only">(current)</span></a>
                        <a class="nav-item nav-link" href="{{ url_for('info.informacije') }}">Info</a>
                        <a class="nav-item nav-link" href="{{ url_for('offenses.all_offenses') }}">Offensi</a>
                        <a class="nav-item nav-link" href="{{ url_for('stats.statistika') }}">Statistika</a>
                        <a class="nav-item nav-link" href="{{ url_for('apis.APIs') }}">APIs</a>
                    </div>
                    <div class="navbar-nav ml-auto" >
                        {% if current_user.is_authenticated %}
                            <a class="nav-item nav-link ml-auto material-icons" href="{{ url_for('users.profil', username=current_user.username) }}">settings</a>
                            <a class="nav-item nav-link ml-auto" href="{{ url_for('users.logout') }}" >Log out</a>
                        {% else %}
                            <a class="nav-item nav-link ml-auto" href="{{ url_for('users.login') }}" >Log in</a>
                        {% endif %}
                    </div>
                </div>
            </nav>

        </header>

        <main class="container-fluid">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="aler alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            <div class="px-3 py-2">
                {% block body %} {% endblock body %}
            </div>
        </main>

        <!-- Javascript - optional -->
        {% block optional_js %} {%endblock optional_js %}

        <footer id="main-footer" class="container-xl footer">
            <div class="container-fluid">
                <div class="row text-muted">
                    <div class="col-6 text-left">
                        <ul class="list-inline">
                            <li class="list-inline-item">
                                <a class="text-muted" href="#">Podpora</a>
                            </li>
                            <li class="list-inline-item">
                                <a class="text-muted" href="#">Zasebnost</a>
                            </li>
                            <li class="list-inline-item">
                                <a class="text-muted" href="#">Pogoji storitve</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-6 text-right">
                        <p class="mb-0">
                            &copy; 2020 - <a href="index.html" class="text-muted">tsdashboard</a>
                        </p>
                    </div>
                </div>
            </div>
        </footer>






    </body>
</html>

tsdashboard/templates/scheduler.html
{% extends "layout.html" %}
{% block head %}
<!-- <meta http-equiv="refresh" content="60" > -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/jobs.css') }}" integrity="" crossorigin="anonymous">
<script src="{{ url_for('static', filename='js/jobs.js') }}" integrity="" crossorigin="anonymous"></script>
{% endblock head %}

{% block body %}
{{ test_tmp }}

<div class="tab">
    <button class="tablinks" onclick="openJobs(event, 'seznam')" id="defaultOpen">Seznam</button>
    <button class="tablinks" onclick="openJobs(event, 'dodaj')">Dodaj</button>
    <button class="tablinks" onclick="openJobs(event, 'popravi')" id="btnEdit">Edit</button>
</div>

<div id="seznam" class="tabcontent">
    <table id="timersTableID">
        <tr>
            <td>ID</td>
            <td>ime</td>
            <td>trigger</td>
            <td>naslednji zagon</td>
            <td>funkcija</td>
            <td>pavza/nadaljuj</td>
            <td>zbriši</td>
        </tr>
        {% for job in jobs %}
        <tr>
            <td>{{ job.id }}</td>
            <td>{{ job.name }}</td>
            <td>{{ job.trigger }}</td>
            <td>{{ job.next_run_time }}</td>
            <td>{{ job.func_ref }}</td>
            <!-- <td><button type="submit" id="btnPause" class="material-icons">pause_circle_outline</button></td> -->
            {% if job.next_run_time is none %}
                <td><a href="{{ url_for('timers.resume_timer', id=job.id) }}" id="btn-pause-{{ job.id }}" class="btn material-icons">play_circle_outline</a></td>
            {% else %}
                <td><a href="{{ url_for('timers.pause_timer', id=job.id) }}" id="btn-pause-{{ job.id }}" class="btn material-icons">pause_circle_outline</a></td>
            {% endif %}
            <!-- <td><button type="submit" id="btnEdit" name="{{ job.id }}" class="material-icons">edit</button></td> -->
            <!-- <td><button type="submit" id="btnDelete" name="{{ job.id }}" class="material-icons">delete_outline</button></td> -->
            <td><a href="{{ url_for('timers.delete_timer', id=job.id) }}" id="btn-delete-{{ job.id }}" class="btn material-icons">delete_outline</a></td>
        </tr>
        {% endfor %}
    </table>
</div>
  
<div id="dodaj" class="tabcontent">
    <table id="timersAddTableID">
        <tr>
            <td>ID</td>
            <td>ime</td>
            <td>trigger</td>
            <td>funkcija</td>
        </tr>
        <tr>
            <td><input type="text" id="timerID"></td>
            <td><input type="text"></td>
            <td>
                <select name="triggerSelect" id="trigerSelect" onchange="triggerFunc()">
                    <option value="" selected disabled>Izberi vrsto</option>
                    <option value="interval">Interval Trigger</option>
                    <option value="cron">Cron Trigger</option>
                </select>
                <!-- <input type="text" id="triggerInput"> -->
            </td>
            <td><input type="text"></td>
            <td><button id="btnAdd" class="material-icons">add_circle_outline</button></td>
            <td><button id="btnAdd" class="material-icons">save</button></td>
            <td><button id="btnAdd" class="material-icons">autorenew</button></td>
            <td><button id="btnAdd" class="material-icons">remove_circle_outline</button></td>
        </tr>
    </table>
</div>
  
<div id="popravi" class="tabcontent">
    <!-- <form action="{{ url_for('timers.edit_timer', id=jobID) }}" method="post"> -->
        <form action="#" id="editForm" method="post">
        <table id="timersEditTableID">
            <tr>
                <td>ID</td>
                <td>ime</td>
                <td>trigger</td>
                <td>naslednji zagon</td>
                <td>funkcija</td>
                <td>shrani</td>
                <!-- <td>pavza/nadaljuj</td> -->
                <!-- <td>popravi</td> -->
                <!-- <td>zbriši</td> -->
            </tr>
        </table>
    </form>
</div>


    
    <br>
    
{% endblock body %}

{% block optional_js %}
<script>
    // tmp = [];
    // {% for job in jobs %}
    //     tmp[{{ loop.index0 }}] = ["{{ job.id }}", "{{ job.name }}", "{{ job.trigger }}", "{{ job.next_run_time }}", "{{ job.func_ref }}"];
    // {% endfor %}
    // jobFunction(tmp);
</script>
{%endblock optional_js %}